### ISSUE TITLE
jar-utilities problem with TYPO3 Console

### ISSUE THREAD

**Issue by martin-git-kristensen** [invokablegmbh/jar-utilities#2]
I have the extension https://extensions.typo3.org/extension/typo3_console installed - but I get this error in ssh terminal from the extension when jar-utilities and jar-columnrow and flex is installed too.

In Typo3 backend and frontend there is no problems or errors :-)

![billede](https://user-images.githubusercontent.com/54167636/196891698-41da29a1-8d67-415b-a2ab-53071fbf4887.png)

**Comment by invokablegmbh** [comment]
Thanks for your Feedback. We implemented a Fix for it in Version 1.0.32 you can update it in a few minutes :)

**Comment by invokablegmbh** [comment]
Version 1.0.32 is released, looking forward for your Feedback!

**Comment by martin-git-kristensen** [comment]
Version 1.0.32 did corrected the error mentioned above - thanks for your word - very nice extension :-)

**Comment by invokablegmbh** [comment]
Thanks a lot!
